/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { db } from "./firebase";
import { collection, doc, setDoc, getDocs, limit, query } from "firebase/firestore";
import { CommunityAgent, SubmissionStatus, SubmissionMethod } from "../types";
import { seedAgents } from "./seeds";

// The single admin account permitted to create/delete shared communityAgents docs (FINDING-1).
// MUST stay in sync with the isAdmin() UID literal in firestore.rules. The UID is NOT secret —
// security is enforced by the rule, not by hiding this value. Regular users only read the pool.
export const ADMIN_UID = "r8kbaKbmguNfaoJTb9wH4BetJab2";

// Defined list of 25 community agent seed records as requested
export const customCommunitySeedRecords: CommunityAgent[] = [
  {
    id: "ca-helena-marsh",
    name: "Helena Marsh",
    agency: "Northlight Literary",
    email: "hmarsh@northlightlit.com",
    website: "northlightlit.com",
    genres: ["Historical Fiction", "Literary Fiction", "Fantasy", "Adult"],
    mswlNotes: "Seeking atmospheric historical settings with a strong sense of place, complex female protagonists, and stories that weave magic into the mundane. Particularly drawn to Victorian and Edwardian England, unreliable narrators, and slow-burn romance subplots.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-15T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-15T00:00:00Z",
    lastCheckedDate: "2026-03-15T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-james-calloway",
    name: "James Calloway",
    agency: "Meridian Books Agency",
    email: "jcalloway@meridianbooksagency.com",
    website: "meridianbooksagency.com",
    genres: ["Thriller", "Crime", "Mystery", "Adult"],
    mswlNotes: "Looking for propulsive thrillers with morally complex protagonists, procedural crime novels with heart, and psychological mysteries that subvert expectations. Love unreliable narrators, twisty plots, and stories set outside the US.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 8,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-01T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-01T00:00:00Z",
    lastCheckedDate: "2026-04-01T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-priya-anand",
    name: "Priya Anand",
    agency: "The Story Collective",
    email: "panand@storycollective.co.uk",
    website: "storycollective.co.uk",
    country: "GB",
    genres: ["Literary Fiction", "Memoir", "Narrative Non-fiction", "Adult"],
    mswlNotes: "Passionate about stories from underrepresented voices, lyrical literary fiction that pushes form, and memoirs with a strong authorial perspective. Interested in the intersection of culture, identity, and belonging. Love books that feel urgent and necessary.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 12,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.ONLINE_FORM,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-02-20T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-02-20T00:00:00Z",
    lastCheckedDate: "2026-02-20T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-tom-ashworth",
    name: "Tom Ashworth",
    agency: "Ashworth & Reed Literary",
    email: "tashworth@ashworthreed.com",
    website: "ashworthreed.com",
    genres: ["Fantasy", "Science Fiction", "Adult", "Young Adult"],
    mswlNotes: "Seeking epic fantasy with intricate world-building and political depth, science fiction that uses speculative elements to explore human nature, and any story that makes me see the world differently. Big fan of found family narratives, anti-heroes, and prose that sings.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 14,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-30T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-30T00:00:00Z",
    lastCheckedDate: "2026-03-30T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-cassandra-vole",
    name: "Cassandra Vole",
    agency: "The Inkwell Agency",
    email: "cvole@inkwellagency.co.uk",
    website: "inkwellagency.co.uk",
    country: "GB",
    genres: ["Romance", "Historical Fiction", "Young Adult", "Adult"],
    mswlNotes: "Looking for swoony historical romance with feminist sensibility, contemporary YA with real emotional depth, and any love story that makes me cry on public transport. Particularly interested in diverse casts and non-Western settings.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 6,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-10T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-10T00:00:00Z",
    lastCheckedDate: "2026-04-10T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-rupert-hale",
    name: "Rupert Hale",
    agency: "Sovereign Literary Management",
    email: "rhale@sovereignlit.com",
    website: "sovereignlit.com",
    genres: ["Historical Fiction", "Fantasy", "Horror", "Adult"],
    mswlNotes: "Drawn to dark historical fiction with gothic atmosphere, fantasy rooted in folklore and mythology, and literary horror that gets under the skin. Love morally ambiguous characters, slow dread, and endings that linger. Particularly interested in British and Irish settings.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 16,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-01-15T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-01-15T00:00:00Z",
    lastCheckedDate: "2026-01-15T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-diane-osei",
    name: "Diane Osei",
    agency: "Page & Pen Associates",
    email: "dosei@pageandpen.co.uk",
    website: "pageandpen.co.uk",
    country: "GB",
    genres: ["Literary Fiction", "Commercial Fiction", "Adult", "Young Adult"],
    mswlNotes: "Seeking commercial fiction with literary sensibility, stories about family and intergenerational trauma, and novels that balance plot and character in equal measure. Interested in African and Caribbean diaspora stories, domestic noir, and anything with an unforgettable voice.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.ONLINE_FORM,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-05T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-05T00:00:00Z",
    lastCheckedDate: "2026-03-05T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-felix-crane",
    name: "Felix Crane",
    agency: "Crane Literary",
    email: "fcrane@craneliterary.com",
    website: "craneliterary.com",
    genres: ["Science Fiction", "Thriller", "Adult"],
    mswlNotes: "Looking for near-future science fiction grounded in real science, techno-thrillers with global stakes, and stories that ask hard questions about technology and humanity. Love unreliable systems, conspiracy plots, and endings that reframe everything.",
    submissionStatus: SubmissionStatus.CLOSED,
    responseTimeWeeks: 12,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis"],
    starRating: 3,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-02-01T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-02-01T00:00:00Z",
    lastCheckedDate: "2026-02-01T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-nora-blackwell",
    name: "Nora Blackwell",
    agency: "Blackwell & Stone",
    email: "nblackwell@blackwellstone.com",
    website: "blackwellstone.com",
    genres: ["Middle Grade", "Young Adult", "Fantasy", "Adventure"],
    mswlNotes: "Passionate about middle grade adventures with big hearts, YA fantasy where the stakes feel real, and any story with a protagonist who grows through genuine struggle. Love talking animals, found family, and magic systems that feel earned.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 8,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-05T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-05T00:00:00Z",
    lastCheckedDate: "2026-04-05T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-georgina-tate",
    name: "Georgina Tate",
    agency: "Tate Literary Group",
    email: "gtate@tateliterarygroup.com",
    website: "tateliterarygroup.com",
    genres: ["Historical Fiction", "Literary Fiction", "Memoir", "Adult"],
    mswlNotes: "Seeking richly researched historical fiction that illuminates forgotten voices, literary memoirs with universal resonance, and novels that use the past to speak to the present. Particularly interested in women's stories across history and books that challenge the official record.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 14,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-20T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-20T00:00:00Z",
    lastCheckedDate: "2026-03-20T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-alastair-drummond",
    name: "Alastair Drummond",
    agency: "Drummond & Fox",
    email: "adrummond@drummondfox.com",
    website: "drummondfox.com",
    genres: ["Crime", "Thriller", "Historical Fiction", "Adult"],
    mswlNotes: "Looking for British crime fiction with a strong sense of place, historical thrillers with page-turning pace, and detective novels that subvert the genre. Love an unconventional investigator, a deeply atmospheric setting, and plots that feel airtight.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-02-28T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-02-28T00:00:00Z",
    lastCheckedDate: "2026-02-28T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-simone-laurent",
    name: "Simone Laurent",
    agency: "Laurent Literary",
    email: "slaurent@laurentlit.com",
    website: "laurentlit.com",
    genres: ["Literary Fiction", "Fantasy", "Adult", "Young Adult"],
    mswlNotes: "Drawn to literary fantasy that blurs genre boundaries, fiction about artists and creative life, and stories told in unusual structures or forms. Interested in European settings, magical realism, and books that feel like they could only have been written by one specific person.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 12,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.ONLINE_FORM,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-12T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-12T00:00:00Z",
    lastCheckedDate: "2026-04-12T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-patrick-doherty",
    name: "Patrick Doherty",
    agency: "Doherty & Wren",
    email: "pdoherty@dohertywren.ie",
    website: "dohertywren.ie",
    country: "IE",
    genres: ["Literary Fiction", "Historical Fiction", "Adult"],
    mswlNotes: "Seeking Irish and British literary fiction with strong rural or small-town settings, historical novels rooted in the nineteenth and early twentieth century, and stories about ordinary people in extraordinary circumstances. Love quiet devastation, earned endings, and prose with real rhythm.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 16,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-01-30T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-01-30T00:00:00Z",
    lastCheckedDate: "2026-01-30T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-miriam-goldstein",
    name: "Miriam Goldstein",
    agency: "The Manuscript Agency",
    email: "mgoldstein@manuscriptagency.com",
    website: "manuscriptagency.com",
    genres: ["Commercial Fiction", "Romance", "Adult"],
    mswlNotes: "Looking for smart commercial fiction with strong hooks, women's fiction about reinvention and second chances, and romance with genuine emotional stakes. Love a dual timeline, a big secret, and endings that feel both surprising and inevitable.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 8,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Sample Pages"],
    starRating: 3,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-10T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-10T00:00:00Z",
    lastCheckedDate: "2026-03-10T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-oliver-fenn",
    name: "Oliver Fenn",
    agency: "Fenn & Associates",
    email: "ofenn@fennassociates.co.uk",
    website: "fennassociates.co.uk",
    country: "GB",
    genres: ["Fantasy", "Horror", "Adult", "Young Adult"],
    mswlNotes: "Passionate about horror that uses fear to say something true about the world, dark fantasy with folkloric roots, and stories that don't flinch from difficult material. Particularly interested in British folk horror, cosmic dread, and anything that genuinely unsettles me.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-08T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-08T00:00:00Z",
    lastCheckedDate: "2026-04-08T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-clara-whitmore",
    name: "Clara Whitmore",
    agency: "Whitmore Literary",
    email: "cwhitmore@whitmoreliterary.com",
    website: "whitmoreliterary.com",
    genres: ["Young Adult", "Middle Grade", "Contemporary", "Fantasy"],
    mswlNotes: "Seeking YA contemporary with authentic teen voices and real emotional complexity, middle grade fantasy with humour and heart, and any story featuring neurodivergent protagonists done with sensitivity and specificity. Love books that feel like they were written for one particular reader.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 8,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.ONLINE_FORM,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-25T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-25T00:00:00Z",
    lastCheckedDate: "2026-03-25T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-sebastian-cross",
    name: "Sebastian Cross",
    agency: "Cross & Partners",
    email: "scross@crosspartners.com",
    website: "crosspartners.com",
    genres: ["Science Fiction", "Fantasy", "Adult"],
    mswlNotes: "Looking for hard science fiction with genuinely rigorous ideas, secondary world fantasy with political complexity and no chosen ones, and speculative fiction that takes its premise seriously. Love morally grey factions, unreliable history, and stories where the world-building serves the theme.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 14,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-02-14T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-02-14T00:00:00Z",
    lastCheckedDate: "2026-02-14T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-aoife-murphy",
    name: "Aoife Murphy",
    agency: "Murphy Literary",
    email: "amurphy@murphyliterary.ie",
    website: "murphyliterary.ie",
    country: "IE",
    genres: ["Literary Fiction", "Commercial Fiction", "Adult", "Young Adult"],
    mswlNotes: "Passionate about books with an unmistakable sense of voice, fiction that explores class and social mobility, and YA that takes its readers seriously. Particularly interested in working-class narratives, stories set in Ireland or the UK, and anything that makes me laugh and cry in the same chapter.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-02T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-02T00:00:00Z",
    lastCheckedDate: "2026-04-02T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-hugo-pemberton",
    name: "Hugo Pemberton",
    agency: "Pemberton & Gray",
    email: "hpemberton@pembertongray.com",
    website: "pembertongray.com",
    genres: ["Historical Fiction", "Adventure", "Adult"],
    mswlNotes: "Seeking historical adventure with cinematic scope, naval and military fiction rooted in meticulous research, and stories set in the age of exploration and empire told with a modern sensibility. Love an ensemble cast, a vividly realised period, and plots that move.",
    submissionStatus: SubmissionStatus.CLOSED,
    responseTimeWeeks: 12,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis"],
    starRating: 3,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-01-20T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-01-20T00:00:00Z",
    lastCheckedDate: "2026-01-20T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-lena-hoffman",
    name: "Lena Hoffman",
    agency: "Hoffman Literary Group",
    email: "lhoffman@hoffmanlit.com",
    website: "hoffmanlit.com",
    genres: ["Thriller", "Psychological Fiction", "Adult"],
    mswlNotes: "Looking for domestic thrillers with razor-sharp tension, psychological fiction that gets inside a character's head and stays there, and any story where I genuinely cannot tell who to trust. Love an unreliable narrator, a tightly controlled timeline, and reveals that reframe everything.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 8,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-18T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-18T00:00:00Z",
    lastCheckedDate: "2026-03-18T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-beatrice-langley",
    name: "Beatrice Langley",
    agency: "Langley & Moore",
    email: "blangley@langleymoore.co.uk",
    website: "langleymoore.co.uk",
    country: "GB",
    genres: ["Fantasy", "Historical Fiction", "Adult", "Young Adult"],
    mswlNotes: "Drawn to fantasy that draws on non-Western mythologies and folklore, historical fiction set outside Western Europe, and stories that centre characters typically excluded from the genre. Particularly interested in steampunk, clockpunk, and speculative Victorian fiction with diverse casts.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 12,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.ONLINE_FORM,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-14T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-14T00:00:00Z",
    lastCheckedDate: "2026-04-14T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-richard-stowe",
    name: "Richard Stowe",
    agency: "Stowe Literary",
    email: "rstowe@stoweliterary.com",
    website: "stoweliterary.com",
    genres: ["Crime", "Mystery", "Adult"],
    mswlNotes: "Seeking cosy mysteries with genuine wit and an irresistible amateur sleuth, procedural crime with authentic police work, and any mystery where the setting feels like a character in itself. Love a series with legs, an ensemble of recurring characters, and clues that feel fair.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 3,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-02-22T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-02-22T00:00:00Z",
    lastCheckedDate: "2026-02-22T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-valentina-cruz",
    name: "Valentina Cruz",
    agency: "Cruz Literary",
    email: "vcruz@cruzlit.com",
    website: "cruzlit.com",
    genres: ["Literary Fiction", "Magical Realism", "Adult"],
    mswlNotes: "Passionate about magical realism that uses the fantastical to illuminate emotional truth, literary fiction in translation or inspired by non-English language traditions, and stories about grief, memory, and the persistence of the past. Love beautiful sentences, ambiguous endings, and books that haunt me.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 14,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-03-28T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-03-28T00:00:00Z",
    lastCheckedDate: "2026-03-28T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-marcus-holloway",
    name: "Marcus Holloway",
    agency: "Holloway & Kent",
    email: "mholloway@hollowaykent.com",
    website: "hollowaykent.com",
    genres: ["Horror", "Thriller", "Adult"],
    mswlNotes: "Looking for literary horror that takes the genre seriously, thrillers with genuine dread rather than just pace, and any story that taps into primal fears in an unexpected way. Particularly interested in ecological horror, body horror, and stories where the monster is also sympathetic.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 10,
    noResponseMeansNo: true,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 4,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-06T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-06T00:00:00Z",
    lastCheckedDate: "2026-04-06T00:00:00Z",
    notes: ""
  },
  {
    id: "ca-isobel-grant",
    name: "Isobel Grant",
    agency: "Grant & Sinclair",
    email: "igrant@grantsinclair.co.uk",
    website: "grantsinclair.co.uk",
    country: "GB",
    genres: ["Historical Fiction", "Fantasy", "Literary Fiction", "Adult"],
    mswlNotes: "Seeking historical fiction set in Scotland and the wider British Isles, fantasy rooted in Celtic and Norse mythology, and literary novels that explore the tension between tradition and modernity. Love a strong sense of landscape, stories told across generations, and prose with real music to it. Particularly drawn to clockwork worlds, mechanical magic, and Victorian settings with a dark heart.",
    submissionStatus: SubmissionStatus.OPEN,
    responseTimeWeeks: 12,
    noResponseMeansNo: false,
    submissionMethod: SubmissionMethod.EMAIL,
    materialsWanted: ["Query Letter", "Synopsis", "Sample Pages"],
    starRating: 5,
    dataSource: "seed" as const,
    lastVerifiedDate: "2026-04-15T00:00:00Z",
    contributedByCount: 0,
    communityQueryCount: 0,
    dateAdded: "2026-04-15T00:00:00Z",
    lastCheckedDate: "2026-04-15T00:00:00Z",
    notes: ""
  }
];

// Combine the existing seedAgents maps with custom community seed entries
export const localSeedCommunityAgents: CommunityAgent[] = [
  ...seedAgents.map(agent => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { userId, ...rest } = agent;
    return {
      ...rest,
      contributedByCount: 1,
      lastVerifiedDate: new Date().toISOString(),
      dataSource: "seed" as const,
      communityQueryCount: 0
    };
  }),
  ...customCommunitySeedRecords
];

/**
 * Checks whether the communityAgents collection already has documents,
 * and if not (or if some specific records are missing), writes the local seed records to Firestore.
 */
export async function seedCommunityAgentsIfEmpty(currentUid?: string): Promise<void> {
  // Writes to communityAgents are admin-only (FINDING-1). Regular users only read the already-
  // populated pool — never attempt the seed write, so they get no permission-denied noise.
  if (currentUid !== ADMIN_UID) {
    return;
  }
  try {
    const collRef = collection(db, "communityAgents");
    const qSnapshot = await getDocs(collRef);
    const existingIds = new Set(qSnapshot.docs.map(d => d.id));

    let seededCount = 0;
    for (const communityAgent of localSeedCommunityAgents) {
      if (!existingIds.has(communityAgent.id)) {
        await setDoc(doc(db, "communityAgents", communityAgent.id), communityAgent);
        seededCount++;
      }
    }
    if (seededCount > 0) {
      console.log(`[ScriptAlly Seeding] Seeded ${seededCount} missing community agent records.`);
    }
  } catch (error) {
    console.error("[ScriptAlly Seeding] Failed seeding communityAgents collection:", error);
  }
}
