import { readFileSync, existsSync } from "node:fs";
import { initializeApp } from "firebase/app";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { getFirestore, collection, getDocs } from "firebase/firestore";
const envFile = (f) => Object.fromEntries(readFileSync(f,"utf8").split("\n").map(l=>l.trim()).filter(l=>l&&!l.startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i),l.slice(i+1).replace(/^["']|["']$/g,"")];}));
const dev = envFile(".env.development");
const local = existsSync(".env.local") ? envFile(".env.local") : {};
if (dev.VITE_FIREBASE_PROJECT_ID !== "scriptally-dev") throw new Error("not dev");
const app = initializeApp({ apiKey: dev.VITE_FIREBASE_API_KEY, authDomain: dev.VITE_FIREBASE_AUTH_DOMAIN, projectId: dev.VITE_FIREBASE_PROJECT_ID, storageBucket: dev.VITE_FIREBASE_STORAGE_BUCKET, messagingSenderId: dev.VITE_FIREBASE_MESSAGING_SENDER_ID, appId: dev.VITE_FIREBASE_APP_ID });
const dbId = dev.VITE_FIREBASE_DATABASE_ID;
const db = !dbId || dbId === "(default)" ? getFirestore(app) : getFirestore(app, dbId);
const { user } = await signInWithEmailAndPassword(getAuth(app), process.env.SA_E2E_EMAIL ?? "harness@scriptally.test", process.env.SA_E2E_PASSWORD ?? local.SA_E2E_PASSWORD);
const uid = user.uid;
const pk = await getDocs(collection(db,"users",uid,"packages"));
const qs = await getDocs(collection(db,"users",uid,"queries"));
const linked = {};
qs.docs.forEach(d=>{const p=d.data().packageId; if(p) linked[p]=(linked[p]||0)+1;});
console.log("packages:");
pk.docs.forEach(d=>{const x=d.data();
  console.log(`  ${d.id.padEnd(14)} stamped=${x.firstSentAt ? x.firstSentAt.slice(0,19) : "NO".padEnd(19)}  linked-queries=${linked[d.id]||0}  name="${x.packageName}"`);});
const stampedNoSends = pk.docs.filter(d=>d.data().firstSentAt && !(linked[d.id]));
const sendsNoStamp   = pk.docs.filter(d=>!d.data().firstSentAt && (linked[d.id]||0)>0);
console.log(`\n⚠️ stamped with NO linked sends: ${stampedNoSends.length}`);
console.log(`⚠️ has linked sends but UNSTAMPED: ${sendsNoStamp.map(d=>d.id).join(", ")||"none"}`);
process.exit(0);
